create type public.app_role as enum (
  'customer',
  'merchant_owner',
  'merchant_staff',
  'driver',
  'admin'
);

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  phone_number text,
  avatar_url text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.user_roles (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  role public.app_role not null,
  created_at timestamptz not null default now(),
  unique(user_id, role)
);

create table public.addresses (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  label text,
  address_line text not null,
  city text,
  latitude double precision,
  longitude double precision,
  is_default boolean not null default false,
  created_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (
    id,
    full_name,
    phone_number
  )
  values (
    new.id,
    new.raw_user_meta_data ->> 'full_name',
    new.phone
  );

  insert into public.user_roles (
    user_id,
    role
  )
  values (
    new.id,
    'customer'
  );

  return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.user_roles enable row level security;
alter table public.addresses enable row level security;

create policy "Users can view own profile"
on public.profiles
for select
using (auth.uid() = id);

create policy "Users can update own profile"
on public.profiles
for update
using (auth.uid() = id)
with check (auth.uid() = id);

create policy "Users can view own roles"
on public.user_roles
for select
using (auth.uid() = user_id);

create policy "Users can view own addresses"
on public.addresses
for select
using (auth.uid() = user_id);

create policy "Users can create own addresses"
on public.addresses
for insert
with check (auth.uid() = user_id);

create policy "Users can update own addresses"
on public.addresses
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users can delete own addresses"
on public.addresses
for delete
using (auth.uid() = user_id);